#!/usr/bin/env bash
#
# Create an isolated git worktree for a GitHub issue, with a per-worktree
# .env.worktree.local containing deterministic port offsets, and bootstrap
# the dev stack so `make dev-all` is the only remaining step.
#
# Usage: ./scripts/new-worktree.sh <issue-number>
#
# Set NEW_WORKTREE_SKIP_BOOTSTRAP=1 to skip the docker compose / migrate / seed
# step (used by tests and quick worktree-only setup).
#
# Background: docker-compose project names auto-derive from the worktree
# directory name, so containers, networks, and named volumes are already
# isolated per worktree. The only collision today is host ports — this script
# generates an offset deterministically from the issue number so the same
# issue always lands on the same ports across machines.

set -euo pipefail

issue="${1:-}"
if [[ -z "$issue" ]]; then
  echo "usage: $0 <issue-number>" >&2
  exit 1
fi
issue="${issue#\#}"
if ! [[ "$issue" =~ ^[0-9]+$ ]]; then
  echo "error: issue must be numeric (got '$issue')" >&2
  exit 1
fi
# Canonicalize so /worktree 042 and /worktree 42 produce the same branch, dir,
# and port offset. 10# forces base-10 interpretation (bash treats leading-zero
# strings as octal otherwise — "08" would error).
issue=$((10#$issue))
if (( issue < 1 )); then
  echo "error: issue number must be positive (got '$issue')" >&2
  exit 1
fi

# Derive branch slug to match .claude/commands/issue.md convention exactly:
# lowercase, non-alphanumerics collapsed to single '-', trimmed, capped at 60.
title=$(gh issue view "$issue" --json title --jq .title)
slug=$(printf '%s' "$title" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' \
  | cut -c1-60 \
  | sed -E 's/-+$//')
branch="${issue}-${slug}"

# Worktree lives at <repo>/.worktrees/issue-<n>/ (gitignored). Anchoring to the
# repo root via rev-parse means the script works regardless of cwd. Keeping it
# inside the repo (vs. a sibling like ../gankedtv-issue-<n>/) means VS Code's
# file watcher, search tooling, and any path-relative scripts all stay scoped
# to one directory tree.
repo_root=$(git rev-parse --show-toplevel)
rel_dir=".worktrees/issue-${issue}"
dir="${repo_root}/${rel_dir}"
mkdir -p "${repo_root}/.worktrees"

# Deterministic offset: (sha1(issue) mod 50) * 10  → 0..490, step 10.
# Same issue number → same ports across machines, so devs can predict URLs.
if command -v shasum >/dev/null 2>&1; then
  hex=$(printf '%s' "$issue" | shasum -a 1 | cut -c1-8)
elif command -v sha1sum >/dev/null 2>&1; then
  hex=$(printf '%s' "$issue" | sha1sum | cut -c1-8)
else
  echo "error: need shasum or sha1sum on PATH" >&2
  exit 1
fi
offset=$(( (16#${hex} % 50) * 10 ))

pg=$((5435 + offset))
s3=$((9000 + offset))
s3c=$((9001 + offset))
api=$((5050 + offset))
vite=$((5173 + offset))

if [[ -e "$dir" ]]; then
  echo "error: $dir already exists — remove it first with ./scripts/remove-worktree.sh $issue" >&2
  exit 1
fi

# Port collision check. With a 50-slot offset space, two simultaneously-active
# issues can land on the same offset (~2% chance per pair). Probe each port via
# bash's /dev/tcp pseudo-device (no nc/lsof dependency) and bail with a clear
# message if anything is already listening — better than a confusing compose
# port-bind error mid-bootstrap.
ports_in_use=()
for p in "$pg" "$s3" "$s3c" "$api" "$vite"; do
  if (echo >"/dev/tcp/127.0.0.1/$p") >/dev/null 2>&1; then
    ports_in_use+=("$p")
  fi
done
if (( ${#ports_in_use[@]} > 0 )); then
  echo "error: ports already in use: ${ports_in_use[*]}" >&2
  echo "  another worktree (or unrelated process) is on the same offset." >&2
  echo "  list worktrees: git worktree list" >&2
  echo "  tear one down:  ./scripts/remove-worktree.sh <other-issue>" >&2
  exit 1
fi

git fetch origin --quiet
if git show-ref --verify --quiet "refs/heads/${branch}"; then
  # Branch exists locally — check it out into the worktree without resetting it,
  # so any unpushed work on the branch is preserved. -B would silently reset to
  # origin and drop those commits.
  echo "→ checking out existing local branch $branch"
  git worktree add "$dir" "$branch"
elif git show-ref --verify --quiet "refs/remotes/origin/${branch}"; then
  echo "→ creating local branch $branch tracking origin/${branch}"
  git worktree add -b "$branch" "$dir" "origin/${branch}"
else
  echo "→ creating new branch $branch from origin/main"
  git worktree add -b "$branch" "$dir" origin/main
fi

cat >"$dir/.env.worktree.local" <<EOF
# Auto-generated by scripts/new-worktree.sh for issue #${issue}.
# Deterministic offset = ${offset}. Do not commit (matched by .env.*.local).

# Compose project name — set explicitly because the worktree dir basename is
# "issue-${issue}" (since worktrees live at .worktrees/issue-<n>/), and compose
# would otherwise derive that as the project name. We want the gankedtv- prefix
# to keep containers/volumes/networks visibly scoped to this codebase.
COMPOSE_PROJECT_NAME=gankedtv-issue-${issue}

# docker compose host ports
POSTGRES_HOST_PORT=${pg}
MINIO_API_HOST_PORT=${s3}
MINIO_CONSOLE_HOST_PORT=${s3c}

# host-side process bindings
ASPNETCORE_URLS=http://localhost:${api}
VITE_PORT=${vite}

# cross-process wiring (Program.cs:48,56-66 + web/src/api/client.ts:2 already read these)
DATABASE_URL=Host=localhost;Port=${pg};Database=gankedtv;Username=gankedtv;Password=gankedtv_dev
S3_ENDPOINT=http://localhost:${s3}
VITE_API_BASE_URL=http://localhost:${api}

# CORS + OAuth redirect target. Program.cs always allows WEB_ORIGIN through CORS,
# so the worktree's web (port ${vite}) needs this set or browser→api requests get
# rejected (the default ${WEB_ORIGIN:-http://localhost:5173} points at the main
# checkout's web port).
WEB_ORIGIN=http://localhost:${vite}
EOF

# Seed the worktree's .env from the main checkout so JWT_SECRET, OAuth creds, and
# any other secrets the developer already configured carry over. Without this the
# API fails options validation on first boot (JWT_SECRET must be >= 32 bytes).
# Port-specific overrides live in .env.worktree.local above and win at runtime
# because the Makefile exports them into the shell before dotnet starts, and
# Program.cs's DotNetEnv.NoClobber respects existing env vars.
if [[ -f "${repo_root}/.env" ]]; then
  cp "${repo_root}/.env" "$dir/.env"
  echo "  copied .env from main checkout"
elif command -v openssl >/dev/null 2>&1; then
  # No source .env (fresh clone, CI, or first-time setup). Generate a self-contained
  # one so the worktree boots; the developer can swap in real OAuth creds later.
  jwt_secret=$(openssl rand -hex 32)
  oauth_secret=$(openssl rand -hex 32)
  cat >"$dir/.env" <<EOF
# Auto-generated by scripts/new-worktree.sh — no .env found at ${repo_root}/.env.
# Replace with shared dev secrets if you want parity with main; otherwise treat
# this worktree as a self-contained sandbox.
ASPNETCORE_ENVIRONMENT=Development
JWT_SECRET=${jwt_secret}
OAUTH_STATE_SECRET=${oauth_secret}
EOF
  echo "  generated fresh .env (no source at ${repo_root}/.env)"
else
  echo "  warning: ${repo_root}/.env missing and openssl unavailable — API will fail" >&2
  echo "           to start until you create ${dir}/.env with JWT_SECRET (>=32 bytes)." >&2
fi

echo ""
echo "✓ worktree created: ${rel_dir} (branch $branch)"
echo "  postgres :${pg}   minio :${s3}/:${s3c}   api :${api}   web :${vite}"

if [[ "${NEW_WORKTREE_SKIP_BOOTSTRAP:-0}" == "1" ]]; then
  echo ""
  echo "  bootstrap skipped (NEW_WORKTREE_SKIP_BOOTSTRAP=1)."
  echo "  next: cd ${rel_dir} && make up && make migrate && make seed && make dev-all"
  exit 0
fi

echo ""
echo "→ bootstrapping stack (this mirrors 'make setup' minus the destructive clean)..."
(
  cd "$dir"
  make up
  make wait-minio
  make server-install
  make web-install
  make migrate
  make seed
)
echo ""
echo "✓ stack ready."
echo "  next:  cd ${rel_dir} && make dev-all"
echo "  api:   http://localhost:${api}"
echo "  web:   http://localhost:${vite}"

# Auto-open the worktree in an editor if its CLI is on PATH. Defaults to `code`
# (VS Code); set WORKTREE_EDITOR=cursor (or windsurf, code-insiders, etc.) to
# pick a different VS Code-family CLI — they all accept `-n <path>` for a new
# window. Set WORKTREE_NO_OPEN=1 to skip auto-open entirely (CI, dotfile
# automation, or users who'd rather pick their own editor moment).
editor="${WORKTREE_EDITOR:-code}"
if [[ "${WORKTREE_NO_OPEN:-0}" != "1" ]] && command -v "$editor" >/dev/null 2>&1; then
  echo ""
  echo "→ opening in $editor (WORKTREE_EDITOR=<cmd> to override, WORKTREE_NO_OPEN=1 to skip)"
  "$editor" -n "$dir" >/dev/null 2>&1 &
fi
