#!/usr/bin/env bash
#
# Create an isolated git worktree for a GitHub issue, with a per-worktree
# .env.worktree.local containing deterministic port offsets, and bootstrap
# the dev stack so `make dev-all` is the only remaining step.
#
# Usage: ./scripts/new-worktree.sh <issue-number>
#
# Set NEW_WORKTREE_SKIP_BOOTSTRAP=1 to skip the docker compose / migrate / seed
# step (used by tests and quick worktree-only setup).
#
# Background: docker-compose project names auto-derive from the worktree
# directory name, so containers, networks, and named volumes are already
# isolated per worktree. The only collision today is host ports — this script
# generates an offset deterministically from the issue number so the same
# issue always lands on the same ports across machines.

set -euo pipefail

issue="${1:-}"
if [[ -z "$issue" ]]; then
  echo "usage: $0 <issue-number>" >&2
  exit 1
fi
issue="${issue#\#}"
if ! [[ "$issue" =~ ^[0-9]+$ ]]; then
  echo "error: issue must be numeric (got '$issue')" >&2
  exit 1
fi
# Canonicalize so /worktree 042 and /worktree 42 produce the same branch, dir,
# and port offset. 10# forces base-10 interpretation (bash treats leading-zero
# strings as octal otherwise — "08" would error).
issue=$((10#$issue))

# Derive branch slug to match .claude/commands/issue.md convention exactly:
# lowercase, non-alphanumerics collapsed to single '-', trimmed, capped at 60.
title=$(gh issue view "$issue" --json title --jq .title)
slug=$(printf '%s' "$title" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' \
  | cut -c1-60 \
  | sed -E 's/-+$//')
branch="${issue}-${slug}"
dir="../gankedtv-issue-${issue}"

# Deterministic offset: (sha1(issue) mod 50) * 10  → 0..490, step 10.
# Same issue number → same ports across machines, so devs can predict URLs.
if command -v shasum >/dev/null 2>&1; then
  hex=$(printf '%s' "$issue" | shasum -a 1 | cut -c1-8)
elif command -v sha1sum >/dev/null 2>&1; then
  hex=$(printf '%s' "$issue" | sha1sum | cut -c1-8)
else
  echo "error: need shasum or sha1sum on PATH" >&2
  exit 1
fi
offset=$(( (16#${hex} % 50) * 10 ))

pg=$((5435 + offset))
s3=$((9000 + offset))
s3c=$((9001 + offset))
api=$((5050 + offset))
vite=$((5173 + offset))

if [[ -e "$dir" ]]; then
  echo "error: $dir already exists — remove it first with ./scripts/remove-worktree.sh $issue" >&2
  exit 1
fi

# Port collision check. With a 50-slot offset space, two simultaneously-active
# issues can land on the same offset (~2% chance per pair). Probe each port via
# bash's /dev/tcp pseudo-device (no nc/lsof dependency) and bail with a clear
# message if anything is already listening — better than a confusing compose
# port-bind error mid-bootstrap.
ports_in_use=()
for p in "$pg" "$s3" "$s3c" "$api" "$vite"; do
  if (echo >"/dev/tcp/127.0.0.1/$p") >/dev/null 2>&1; then
    ports_in_use+=("$p")
  fi
done
if (( ${#ports_in_use[@]} > 0 )); then
  echo "error: ports already in use: ${ports_in_use[*]}" >&2
  echo "  another worktree (or unrelated process) is on the same offset." >&2
  echo "  list worktrees: git worktree list" >&2
  echo "  tear one down:  ./scripts/remove-worktree.sh <other-issue>" >&2
  exit 1
fi

git fetch origin --quiet
if git show-ref --verify --quiet "refs/heads/${branch}"; then
  # Branch exists locally — check it out into the worktree without resetting it,
  # so any unpushed work on the branch is preserved. -B would silently reset to
  # origin and drop those commits.
  echo "→ checking out existing local branch $branch"
  git worktree add "$dir" "$branch"
elif git show-ref --verify --quiet "refs/remotes/origin/${branch}"; then
  echo "→ creating local branch $branch tracking origin/${branch}"
  git worktree add -b "$branch" "$dir" "origin/${branch}"
else
  echo "→ creating new branch $branch from origin/main"
  git worktree add -b "$branch" "$dir" origin/main
fi

cat >"$dir/.env.worktree.local" <<EOF
# Auto-generated by scripts/new-worktree.sh for issue #${issue}.
# Deterministic offset = ${offset}. Do not commit (matched by .env.*.local).

# docker compose host ports
POSTGRES_HOST_PORT=${pg}
MINIO_API_HOST_PORT=${s3}
MINIO_CONSOLE_HOST_PORT=${s3c}

# host-side process bindings
ASPNETCORE_URLS=http://localhost:${api}
VITE_PORT=${vite}

# cross-process wiring (Program.cs:48,56-66 + web/src/api/client.ts:2 already read these)
DATABASE_URL=Host=localhost;Port=${pg};Database=gankedtv;Username=gankedtv;Password=gankedtv_dev
S3_ENDPOINT=http://localhost:${s3}
VITE_API_BASE_URL=http://localhost:${api}
EOF

echo ""
echo "✓ worktree created: $dir (branch $branch)"
echo "  postgres :${pg}   minio :${s3}/:${s3c}   api :${api}   web :${vite}"

if [[ "${NEW_WORKTREE_SKIP_BOOTSTRAP:-0}" == "1" ]]; then
  echo ""
  echo "  bootstrap skipped (NEW_WORKTREE_SKIP_BOOTSTRAP=1)."
  echo "  next: cd $dir && make up && make migrate && make seed && make dev-all"
  exit 0
fi

echo ""
echo "→ bootstrapping stack (this mirrors 'make setup' minus the destructive clean)..."
(
  cd "$dir"
  make up
  make wait-minio
  make server-install
  make web-install
  make migrate
  make seed
)
echo ""
echo "✓ stack ready."
echo "  next:  cd $dir && make dev-all"
echo "  api:   http://localhost:${api}"
echo "  web:   http://localhost:${vite}"
