// <auto-generated />
using System;
using GankedTV.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GankedTV.Api.Data.Migrations
{
    [DbContext(typeof(GankedTvDbContext))]
    [Migration("20260430210106_AddUserPasswordCredentials")]
    partial class AddUserPasswordCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Clip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short?>("DurationSecs")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_secs");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<short?>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("processing")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailKey")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VideoKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_key");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("public")
                        .HasColumnName("visibility");

                    b.Property<short?>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_clips");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_clips_created_at");

                    b.HasIndex("GameId")
                        .HasDatabaseName("idx_clips_game_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_clips_status")
                        .HasFilter("status = 'ready'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_clips_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_clips_draft_created_at")
                        .HasFilter("status = 'draft'");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("idx_clips_processing_updated_at")
                        .HasFilter("status = 'processing'");

                    b.ToTable("clips", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<int?>("IgdbId")
                        .HasColumnType("integer")
                        .HasColumnName("igdb_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_games_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_games_slug");

                    b.ToTable("games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "League of Legends",
                            Slug = "league-of-legends",
                            Tag = "LOL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Valorant",
                            Slug = "valorant",
                            Tag = "VALORANT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Counter-Strike 2",
                            Slug = "cs2",
                            Tag = "CS2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fortnite",
                            Slug = "fortnite",
                            Tag = "FN"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Apex Legends",
                            Slug = "apex-legends",
                            Tag = "APEX"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rocket League",
                            Slug = "rocket-league",
                            Tag = "RL"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Overwatch 2",
                            Slug = "overwatch-2",
                            Tag = "OW2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dota 2",
                            Slug = "dota-2",
                            Tag = "DOTA2"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Marvel Rivals",
                            Slug = "marvel-rivals",
                            Tag = "RIVALS"
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "ClipId")
                        .HasName("pk_likes");

                    b.HasIndex("ClipId")
                        .HasDatabaseName("ix_likes_clip_id");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("idx_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("discord_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("google_id");

                    b.Property<string>("PasswordAlgo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("password_algo");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_discord_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_google_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_password_hash_algo_paired", "(password_hash IS NULL AND password_algo IS NULL) OR (password_hash IS NOT NULL AND password_algo IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Clip", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clips_games_game_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany("Clips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clips_users_user_id");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Like", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany("Likes")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_clips_clip_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_users_user_id");

                    b.Navigation("Clip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Clip", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Clips");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
