// <auto-generated />
using System;
using GankedTV.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace GankedTV.Api.Data.Migrations
{
    [DbContext(typeof(GankedTvDbContext))]
    [Migration("20260701122008_BoundHashColumns")]
    partial class BoundHashColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("idx_api_keys_key_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_api_keys_user_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Clip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short?>("DurationSecs")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_secs");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<short?>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<string>("ImportSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("import_source_url");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', coalesce(title, '')), 'A') || setweight(to_tsvector('simple', coalesce(description, '')), 'B')", true);

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("share_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("processing")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailKey")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("text")
                        .HasColumnName("video_codec");

                    b.Property<string>("VideoKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_key");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("public")
                        .HasColumnName("visibility");

                    b.Property<short?>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_clips");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_clips_created_at");

                    b.HasIndex("GameId")
                        .HasDatabaseName("idx_clips_game_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_clips_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("ShareCode")
                        .IsUnique()
                        .HasDatabaseName("idx_clips_share_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_clips_status")
                        .HasFilter("status = 'ready'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_clips_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_clips_draft_created_at")
                        .HasFilter("status = 'draft'");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("idx_clips_processing_updated_at")
                        .HasFilter("status = 'processing'");

                    b.ToTable("clips", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ClipStreamJob", b =>
                {
                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ClipId")
                        .HasName("pk_clip_stream_jobs");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("idx_clip_stream_jobs_pending_updated_at")
                        .HasFilter("status = 'pending'");

                    b.ToTable("clip_stream_jobs", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ClipTag", b =>
                {
                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("ClipId", "TagId")
                        .HasName("pk_clip_tags");

                    b.HasIndex("TagId", "ClipId")
                        .HasDatabaseName("idx_clip_tags_tag");

                    b.ToTable("clip_tags", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ClipView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_clip_views");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_clip_views_created_at");

                    b.HasIndex("ClipId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_clip_views_clip_id_created_at");

                    b.ToTable("clip_views", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_comments_user_id");

                    b.HasIndex("ClipId", "CreatedAt")
                        .HasDatabaseName("idx_comments_clip_id");

                    b.HasIndex("ParentId", "CreatedAt")
                        .HasDatabaseName("idx_comments_parent_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.DeviceAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ClientName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceCodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_code");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_authorizations");

                    b.HasIndex("DeviceCodeHash")
                        .IsUnique()
                        .HasDatabaseName("idx_device_authorizations_device_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_device_authorizations_expires_at");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("idx_device_authorizations_user_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_device_authorizations_user_id");

                    b.ToTable("device_authorizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_authorizations_status", "status IN ('pending','approved','denied')");
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FolloweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("followee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FollowerId", "FolloweeId")
                        .HasName("pk_follows");

                    b.HasIndex("FolloweeId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_follows_followee_created_at");

                    b.HasIndex("FollowerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_follows_follower_created_at");

                    b.ToTable("follows", null, t =>
                        {
                            t.HasCheckConstraint("ck_follows_no_self", "follower_id <> followee_id");
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cover_image_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<int?>("IgdbId")
                        .HasColumnType("integer")
                        .HasColumnName("igdb_id");

                    b.Property<bool>("IgdbManaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("igdb_managed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(name, ''))", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_games_name");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_games_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_games_slug");

                    b.ToTable("games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IgdbManaged = false,
                            Name = "League of Legends",
                            Slug = "league-of-legends",
                            Tag = "LOL"
                        },
                        new
                        {
                            Id = 2,
                            IgdbManaged = false,
                            Name = "Valorant",
                            Slug = "valorant",
                            Tag = "VALORANT"
                        },
                        new
                        {
                            Id = 3,
                            IgdbManaged = false,
                            Name = "Counter-Strike 2",
                            Slug = "cs2",
                            Tag = "CS2"
                        },
                        new
                        {
                            Id = 4,
                            IgdbManaged = false,
                            Name = "Fortnite",
                            Slug = "fortnite",
                            Tag = "FN"
                        },
                        new
                        {
                            Id = 5,
                            IgdbManaged = false,
                            Name = "Apex Legends",
                            Slug = "apex-legends",
                            Tag = "APEX"
                        },
                        new
                        {
                            Id = 6,
                            IgdbManaged = false,
                            Name = "Rocket League",
                            Slug = "rocket-league",
                            Tag = "RL"
                        },
                        new
                        {
                            Id = 7,
                            IgdbManaged = false,
                            Name = "Overwatch 2",
                            Slug = "overwatch-2",
                            Tag = "OW2"
                        },
                        new
                        {
                            Id = 8,
                            IgdbManaged = false,
                            Name = "Dota 2",
                            Slug = "dota-2",
                            Tag = "DOTA2"
                        },
                        new
                        {
                            Id = 9,
                            IgdbManaged = false,
                            Name = "Marvel Rivals",
                            Slug = "marvel-rivals",
                            Tag = "RIVALS"
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "ClipId")
                        .HasName("pk_likes");

                    b.HasIndex("ClipId")
                        .HasDatabaseName("ix_likes_clip_id");

                    b.HasIndex("CreatedAt", "ClipId")
                        .IsDescending(true, false)
                        .HasDatabaseName("idx_likes_created_at_clip_id");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("ClipId")
                        .HasColumnType("uuid")
                        .HasColumnName("clip_id");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_notifications_actor_id");

                    b.HasIndex("ClipId")
                        .HasDatabaseName("ix_notifications_clip_id");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_notifications_comment_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("idx_notifications_unread")
                        .HasFilter("read_at IS NULL");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_notifications_recipient");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_no_self", "actor_id <> recipient_id");
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("idx_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_reports_resolved_by");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_reports_status_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("idx_reports_target");

                    b.HasIndex("ReporterId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("idx_reports_open_unique")
                        .HasFilter("status = 'open'");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_other_note", "reason <> 'other' OR (note IS NOT NULL AND LENGTH(TRIM(note)) > 0)");

                            t.HasCheckConstraint("ck_reports_reason", "reason IN ('spam','harassment','hate','nsfw','violence','wrong_game','other')");

                            t.HasCheckConstraint("ck_reports_status", "status IN ('open','resolved','dismissed')");

                            t.HasCheckConstraint("ck_reports_target_type", "target_type IN ('clip','comment','user')");
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_color");

                    b.Property<string>("AvatarObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("avatar_object_key");

                    b.Property<string>("AvatarSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("avatar_source");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("BannedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("banned_reason");

                    b.Property<string>("BannerObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("banner_object_key");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text")
                        .HasColumnName("banner_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("discord_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("google_id");

                    b.Property<string>("OAuthAvatarSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("oauth_avatar_source");

                    b.Property<string>("OAuthAvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("oauth_avatar_url");

                    b.Property<string>("PasswordAlgo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("password_algo");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_discord_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_google_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_accent_color", "accent_color IS NULL OR accent_color ~ '^#[0-9A-Fa-f]{6}$'");

                            t.HasCheckConstraint("ck_users_password_hash_algo_paired", "(password_hash IS NULL AND password_algo IS NULL) OR (password_hash IS NOT NULL AND password_algo IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_role", "role IN ('user','moderator','admin')");
                        });
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ApiKey", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Clip", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clips_games_game_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany("Clips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clips_users_user_id");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ClipStreamJob", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_stream_jobs_clips_clip_id");

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ClipTag", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany("ClipTags")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_tags_clips_clip_id");

                    b.HasOne("GankedTV.Api.Data.Entities.Tag", "Tag")
                        .WithMany("ClipTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_tags_tags_tag_id");

                    b.Navigation("Clip");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.ClipView", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clip_views_clips_clip_id");

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Comment", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_clips_clip_id");

                    b.HasOne("GankedTV.Api.Data.Entities.Comment", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_comments_comments_parent_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Clip");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.DeviceAuthorization", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_device_authorizations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Follow", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "Followee")
                        .WithMany("Followers")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_followee_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_follower_id");

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Like", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany("Likes")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_clips_clip_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_users_user_id");

                    b.Navigation("Clip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_actor_id");

                    b.HasOne("GankedTV.Api.Data.Entities.Clip", "Clip")
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_clips_clip_id");

                    b.HasOne("GankedTV.Api.Data.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_comments_comment_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_id");

                    b.Navigation("Actor");

                    b.Navigation("Clip");

                    b.Navigation("Comment");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Report", b =>
                {
                    b.HasOne("GankedTV.Api.Data.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reporter_id");

                    b.HasOne("GankedTV.Api.Data.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reports_users_resolved_by");

                    b.Navigation("Reporter");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.User", b =>
                {
                    b.OwnsOne("GankedTV.Api.Data.Entities.SocialLinks", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Twitch");

                            b1.Property<string>("Twitter");

                            b1.Property<string>("YouTube");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1
                                .ToJson("social_links")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Clip", b =>
                {
                    b.Navigation("ClipTags");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.Tag", b =>
                {
                    b.Navigation("ClipTags");
                });

            modelBuilder.Entity("GankedTV.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Clips");

                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
